/**
 * App player names per season.
 * This is a static copy of the player name arrays from src/data/season_XX/index.ts.
 * Kept here so the scraper scripts don't depend on the Vite/React build.
 *
 * When a new season is added to the app, add its player names here too.
 */
export const APP_PLAYERS: Record<number, string[]> = {
  9: [
    "Brady Finta",
    "Brook Geraghty",
    "Bubba Sampson",
    "Chad Crittenden",
    "Chris Daugherty",
    "John Kenney",
    "John Palyok",
    "Lea Masters",
    "Rory Freeman",
    "Ami Cusack",
    "Dolly Neely",
    "Eliza Orlins",
    "Julie Berry",
    "Leann Slaby",
    "Lisa Keiffer",
    "Mia Galeotalanza",
    "Scout Cloud Lee",
    "Twila Tanner",
  ],
  46: [
    "Ben Katzman",
    "Bhanu Gopal",
    "Charlie Davis",
    "David Jelinsky",
    "Hunter McKnight",
    "Jem Hussain-Adams",
    "Jess Chong",
    "Kenzie Petty",
    "Liz Wilcox",
    "Maria Shrime Gonzalez",
    "Moriah Gaynor",
    "Q Burdette",
    "Randen Montalvo",
    "Soda Thompson",
    "Tevin Davis",
    "Tim Spicer",
    "Venus Vafa",
    "Tiffany Nicole Ervin",
  ],
  50: [
    "Jenna Lewis-Dougherty",
    "Colby Donaldson",
    "Stephenie LaGrossa Kendrick",
    "Cirie Fields",
    "Ozzy Lusth",
    'Benjamin "Coach" Wade',
    "Aubry Bracco",
    "Chrissy Hofbeck",
    "Christian Hubicki",
    "Angelina Keeley",
    "Mike White",
    "Rick Devens",
    "Jonathan Young",
    "Emily Flippen",
    "Dee Valladares",
    'Quintavius "Q" Burdette',
    "Charlie Davis",
    "Tiffany Ervin",
    "Genevieve Mushaluk",
    "Kyle Fraser",
    "Joe Hunter",
    "Kamilla Karthigesu",
    "Savannah Louie",
    "Rizo Velovic",
  ],
};
